version: '2.1'

services:
  
  etl_process:
    build: .
    command: sh -c 'sleep 30s && python ./scripts/create_tables_script.py && python ./jobs/city_info_job.py && python job_scheduler.py'
    volumes:
      - ./:/src
    env_file:
      - infra/venvs.env

  db:
    image: postgres:9.4.15
    stdin_open: true
    environment:
     - POSTGRES_PASSWORD=123456
     - POSTGRES_USER=user
     - POSTGRES_DB=warehouse
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080